# Generated by Django 5.2 on 2025-07-31 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_provider",
                    models.CharField(
                        blank=True,
                        help_text="User's preferred OAuth provider",
                        max_length=50,
                    ),
                ),
                (
                    "auto_login_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable automatic login with preferred provider",
                    ),
                ),
                ("profile_completed", models.BooleanField(default=False)),
                (
                    "profile_completion_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "share_email",
                    models.BooleanField(
                        default=True,
                        help_text="Allow sharing email with connected apps",
                    ),
                ),
                (
                    "share_profile",
                    models.BooleanField(
                        default=True,
                        help_text="Allow sharing profile info with connected apps",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth User Profile",
                "verbose_name_plural": "OAuth User Profiles",
            },
        ),
        migrations.CreateModel(
            name="OAuthAppConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "permissions_granted",
                    models.JSONField(
                        default=list,
                        help_text="List of permissions granted to this app",
                    ),
                ),
                (
                    "data_access_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Profile"),
                            ("email", "Email Access"),
                            ("full", "Full Profile"),
                            ("custom", "Custom Permissions"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "social_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialaccount.socialapp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth App Connection",
                "verbose_name_plural": "OAuth App Connections",
                "unique_together": {("user", "social_app")},
            },
        ),
        migrations.CreateModel(
            name="OAuthLoginSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="OAuth provider (google, github, etc.)", max_length=50
                    ),
                ),
                (
                    "provider_uid",
                    models.CharField(
                        help_text="User ID from OAuth provider", max_length=255
                    ),
                ),
                ("login_timestamp", models.DateTimeField(auto_now_add=True)),
                ("logout_timestamp", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("access_token_expires", models.DateTimeField(blank=True, null=True)),
                (
                    "scope_granted",
                    models.JSONField(
                        default=list, help_text="OAuth scopes granted by user"
                    ),
                ),
                (
                    "login_method",
                    models.CharField(
                        choices=[
                            ("oauth_new", "OAuth New User"),
                            ("oauth_existing", "OAuth Existing User"),
                            ("oauth_connect", "OAuth Account Connection"),
                        ],
                        default="oauth_existing",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth Login Session",
                "verbose_name_plural": "OAuth Login Sessions",
                "ordering": ["-login_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="oauth_auth__user_id_25aee9_idx",
                    ),
                    models.Index(
                        fields=["provider", "login_timestamp"],
                        name="oauth_auth__provide_abe0d7_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="oauth_auth__session_1b49b4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthSecurityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Success"),
                            ("login_failed", "Login Failed"),
                            ("account_connected", "Account Connected"),
                            ("account_disconnected", "Account Disconnected"),
                            ("permission_granted", "Permission Granted"),
                            ("permission_revoked", "Permission Revoked"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.UUIDField(blank=True, null=True)),
                (
                    "event_data",
                    models.JSONField(
                        default=dict, help_text="Additional event-specific information"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_security_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth Security Log",
                "verbose_name_plural": "OAuth Security Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="oauth_auth__user_id_9d0714_idx",
                    ),
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="oauth_auth__event_t_00f0cc_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "timestamp"],
                        name="oauth_auth__risk_le_f3d626_idx",
                    ),
                ],
            },
        ),
    ]
