# Generated by Django 5.2 on 2025-07-31 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JWTLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField()),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_credentials", "Invalid Credentials"),
                            ("account_disabled", "Account Disabled"),
                            ("rate_limited", "Rate Limited"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        max_length=100,
                    ),
                ),
                ("request_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "JWT Login Attempt",
                "verbose_name_plural": "JWT Login Attempts",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["username", "timestamp"],
                        name="jwt_auth_jw_usernam_8213d6_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="jwt_auth_jw_ip_addr_5f3413_idx",
                    ),
                    models.Index(
                        fields=["success", "timestamp"],
                        name="jwt_auth_jw_success_f02056_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JWTBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jti",
                    models.CharField(
                        db_index=True,
                        help_text="JWT ID (jti claim)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("access", "Access Token"),
                            ("refresh", "Refresh Token"),
                        ],
                        default="access",
                        max_length=20,
                    ),
                ),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the original token would have expired"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual_revoke", "Manual Revocation"),
                            ("logout", "User Logout"),
                            ("security", "Security Concern"),
                            ("expired", "Token Expired"),
                        ],
                        default="manual_revoke",
                        max_length=100,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "JWT Blacklist Entry",
                "verbose_name_plural": "JWT Blacklist Entries",
                "ordering": ["-blacklisted_at"],
                "indexes": [
                    models.Index(fields=["jti"], name="jwt_auth_jw_jti_e58799_idx"),
                    models.Index(
                        fields=["user", "blacklisted_at"],
                        name="jwt_auth_jw_user_id_def6cd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JWTUserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "refresh_jti",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("logout_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jwt_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "JWT User Session",
                "verbose_name_plural": "JWT User Sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="jwt_auth_jw_user_id_3833d5_idx",
                    ),
                    models.Index(
                        fields=["refresh_jti"], name="jwt_auth_jw_refresh_747bf5_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="jwt_auth_jw_session_ef9ede_idx"
                    ),
                ],
            },
        ),
    ]
