# Generated by Django 5.2 on 2025-07-31 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("access", "Access Token"),
                            ("refresh", "Refresh Token"),
                            ("api_key", "API Key"),
                        ],
                        default="access",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this token", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "scopes",
                    models.JSONField(
                        default=list,
                        help_text="List of permissions/scopes for this token",
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "max_usage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of uses (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "ip_whitelist",
                    models.JSONField(
                        default=list, help_text="List of allowed IP addresses"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent when token was created"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token",
                "verbose_name_plural": "API Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=200)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="token_auth.apitoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Usage Log",
                "verbose_name_plural": "Token Usage Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
